#!/bin/sh

# put to /usr/local/bin/tmux_sessions

attach_session() {
    session_name="$1"
    if [ "$TMUX" = "" ]; then
        tmux attach-session -t "$session_name"
    else
        # Check if session exists before switching
        if tmux has-session -t "$session_name" 2>/dev/null; then
            tmux switch-client -t "$session_name"
        else
            echo "Session $session_name does not exist."
        fi
    fi
}
# Function to create or attach to a tmux session
create_or_attach_session() {
    session_name="$1"

    # Check if the session exists
    if tmux has-session -t "$session_name" 2>/dev/null; then
        # If session exists, attach to it
	attach_session "$session_name"
    else
        # If session does not exist, create and attach to it
        tmux new-session -d -s "$session_name"
	attach_session "$session_name"
    fi
}

# Function to kill and potentially restart a tmux session
kill_session() {
    session_name="$1"

    # Kill the session if it exists
    tmux kill-session -t "$session_name" 2>/dev/null
}

# Main script
if [ "$1" = "a" ]; then
    # If 'a' argument is provided, create or attach session
    create_or_attach_session "$2"
elif [ "$1" = "k" ]; then
    # If 'r' argument is provided, kill session
    kill_session "$2"
elif [ "$1" = "l" ]; then
    tmux list-sessions
else
    # If no valid arguments provided, display usage message
    echo "Usage: $0 [a|r|l] session_name"
    echo "  a: create or attach to session"
    echo "  k: kill session (optionally restart if inside)"
    echo "  l: list all sessions"
fi

